baseURL = "http://tproxy/"
languageCode = "en-us"
title = "TProxy"
theme = "hugo-flex"
themesDir = "../../vendor/themes"

[params]
footer = "Copyright (c) by Alexander Pevzner, 2019"

[[menu.nav]]
  name = "Configuration"
  url = "conf/"
  weight = 1

[[menu.nav]]
  name = "Sites"
  url = "sites/"
  weight = 2

[[menu.nav]]
  name = "Keys"
  url = "keys/"
  weight = 3

[[menu.nav]]
  name = "Counters"
  url = "counters/"
  weight = 4


